//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.WebUI.CarWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        private int DriverLicenseAgeField;
        
        private int MinAgeField;
        
        private int DailyKmLimitField;
        
        private int CurrentKmField;
        
        private bool AirbagField;
        
        private int BaggageCapacityField;
        
        private int SeatCountField;
        
        private int DailyPriceField;
        
        private int CompanyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CarName {
            get {
                return this.CarNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarNameField, value) != true)) {
                    this.CarNameField = value;
                    this.RaisePropertyChanged("CarName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int DriverLicenseAge {
            get {
                return this.DriverLicenseAgeField;
            }
            set {
                if ((this.DriverLicenseAgeField.Equals(value) != true)) {
                    this.DriverLicenseAgeField = value;
                    this.RaisePropertyChanged("DriverLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int DailyKmLimit {
            get {
                return this.DailyKmLimitField;
            }
            set {
                if ((this.DailyKmLimitField.Equals(value) != true)) {
                    this.DailyKmLimitField = value;
                    this.RaisePropertyChanged("DailyKmLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CurrentKm {
            get {
                return this.CurrentKmField;
            }
            set {
                if ((this.CurrentKmField.Equals(value) != true)) {
                    this.CurrentKmField = value;
                    this.RaisePropertyChanged("CurrentKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((this.AirbagField.Equals(value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BaggageCapacity {
            get {
                return this.BaggageCapacityField;
            }
            set {
                if ((this.BaggageCapacityField.Equals(value) != true)) {
                    this.BaggageCapacityField = value;
                    this.RaisePropertyChanged("BaggageCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int SeatCount {
            get {
                return this.SeatCountField;
            }
            set {
                if ((this.SeatCountField.Equals(value) != true)) {
                    this.SeatCountField = value;
                    this.RaisePropertyChanged("SeatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int DailyPrice {
            get {
                return this.DailyPriceField;
            }
            set {
                if ((this.DailyPriceField.Equals(value) != true)) {
                    this.DailyPriceField = value;
                    this.RaisePropertyChanged("DailyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarWebService.CarWebServiceSoap")]
    public interface CarWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        AracKiralama.WebUI.CarWebService.GetAllResponse GetAll(AracKiralama.WebUI.CarWebService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.GetAllResponse> GetAllAsync(AracKiralama.WebUI.CarWebService.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AracKiralama.WebUI.CarWebService.UpdateResponse Update(AracKiralama.WebUI.CarWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.UpdateResponse> UpdateAsync(AracKiralama.WebUI.CarWebService.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.CarWebService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(AracKiralama.WebUI.CarWebService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.CarWebService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(AracKiralama.WebUI.CarWebService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.CarWebService.Car[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(AracKiralama.WebUI.CarWebService.Car[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.CarWebService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AracKiralama.WebUI.CarWebService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.CarWebService.Car car;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AracKiralama.WebUI.CarWebService.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.CarWebService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AracKiralama.WebUI.CarWebService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarWebServiceSoapChannel : AracKiralama.WebUI.CarWebService.CarWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralama.WebUI.CarWebService.CarWebServiceSoap>, AracKiralama.WebUI.CarWebService.CarWebServiceSoap {
        
        public CarWebServiceSoapClient() {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.CarWebService.GetAllResponse AracKiralama.WebUI.CarWebService.CarWebServiceSoap.GetAll(AracKiralama.WebUI.CarWebService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public AracKiralama.WebUI.CarWebService.Car[] GetAll() {
            AracKiralama.WebUI.CarWebService.GetAllRequest inValue = new AracKiralama.WebUI.CarWebService.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.CarWebService.GetAllRequestBody();
            AracKiralama.WebUI.CarWebService.GetAllResponse retVal = ((AracKiralama.WebUI.CarWebService.CarWebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.GetAllResponse> AracKiralama.WebUI.CarWebService.CarWebServiceSoap.GetAllAsync(AracKiralama.WebUI.CarWebService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.GetAllResponse> GetAllAsync() {
            AracKiralama.WebUI.CarWebService.GetAllRequest inValue = new AracKiralama.WebUI.CarWebService.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.CarWebService.GetAllRequestBody();
            return ((AracKiralama.WebUI.CarWebService.CarWebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.CarWebService.UpdateResponse AracKiralama.WebUI.CarWebService.CarWebServiceSoap.Update(AracKiralama.WebUI.CarWebService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(AracKiralama.WebUI.CarWebService.Car car) {
            AracKiralama.WebUI.CarWebService.UpdateRequest inValue = new AracKiralama.WebUI.CarWebService.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.CarWebService.UpdateRequestBody();
            inValue.Body.car = car;
            AracKiralama.WebUI.CarWebService.UpdateResponse retVal = ((AracKiralama.WebUI.CarWebService.CarWebServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.UpdateResponse> AracKiralama.WebUI.CarWebService.CarWebServiceSoap.UpdateAsync(AracKiralama.WebUI.CarWebService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.CarWebService.UpdateResponse> UpdateAsync(AracKiralama.WebUI.CarWebService.Car car) {
            AracKiralama.WebUI.CarWebService.UpdateRequest inValue = new AracKiralama.WebUI.CarWebService.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.CarWebService.UpdateRequestBody();
            inValue.Body.car = car;
            return ((AracKiralama.WebUI.CarWebService.CarWebServiceSoap)(this)).UpdateAsync(inValue);
        }
    }
}
