//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.WebUI.RentedCarWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentedCar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RentedCar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int OldKmField;
        
        private int NewKmField;
        
        private decimal PriceField;
        
        private System.DateTime RentDateField;
        
        private System.DateTime DeliveryDateField;
        
        private bool IsActiveField;
        
        private int carIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        private int CustomerTCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OldKm {
            get {
                return this.OldKmField;
            }
            set {
                if ((this.OldKmField.Equals(value) != true)) {
                    this.OldKmField = value;
                    this.RaisePropertyChanged("OldKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NewKm {
            get {
                return this.NewKmField;
            }
            set {
                if ((this.NewKmField.Equals(value) != true)) {
                    this.NewKmField = value;
                    this.RaisePropertyChanged("NewKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime RentDate {
            get {
                return this.RentDateField;
            }
            set {
                if ((this.RentDateField.Equals(value) != true)) {
                    this.RentDateField = value;
                    this.RaisePropertyChanged("RentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((this.DeliveryDateField.Equals(value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int carId {
            get {
                return this.carIdField;
            }
            set {
                if ((this.carIdField.Equals(value) != true)) {
                    this.carIdField = value;
                    this.RaisePropertyChanged("carId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int CustomerTC {
            get {
                return this.CustomerTCField;
            }
            set {
                if ((this.CustomerTCField.Equals(value) != true)) {
                    this.CustomerTCField = value;
                    this.RaisePropertyChanged("CustomerTC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentedCarWebService.RentedCarWebServiceSoap")]
    public interface RentedCarWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        AracKiralama.WebUI.RentedCarWebService.GetAllResponse GetAll(AracKiralama.WebUI.RentedCarWebService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.GetAllResponse> GetAllAsync(AracKiralama.WebUI.RentedCarWebService.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        AracKiralama.WebUI.RentedCarWebService.UpdateResponse Update(AracKiralama.WebUI.RentedCarWebService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.UpdateResponse> UpdateAsync(AracKiralama.WebUI.RentedCarWebService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name car from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        AracKiralama.WebUI.RentedCarWebService.InsertResponse Insert(AracKiralama.WebUI.RentedCarWebService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.InsertResponse> InsertAsync(AracKiralama.WebUI.RentedCarWebService.InsertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(AracKiralama.WebUI.RentedCarWebService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(AracKiralama.WebUI.RentedCarWebService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.RentedCar[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(AracKiralama.WebUI.RentedCarWebService.RentedCar[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(AracKiralama.WebUI.RentedCarWebService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.RentedCar car;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(AracKiralama.WebUI.RentedCarWebService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(AracKiralama.WebUI.RentedCarWebService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.RentedCar car;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public AracKiralama.WebUI.RentedCarWebService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(AracKiralama.WebUI.RentedCarWebService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(bool InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RentedCarWebServiceSoapChannel : AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentedCarWebServiceSoapClient : System.ServiceModel.ClientBase<AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap>, AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap {
        
        public RentedCarWebServiceSoapClient() {
        }
        
        public RentedCarWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentedCarWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentedCarWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentedCarWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.RentedCarWebService.GetAllResponse AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.GetAll(AracKiralama.WebUI.RentedCarWebService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public AracKiralama.WebUI.RentedCarWebService.RentedCar[] GetAll() {
            AracKiralama.WebUI.RentedCarWebService.GetAllRequest inValue = new AracKiralama.WebUI.RentedCarWebService.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.GetAllRequestBody();
            AracKiralama.WebUI.RentedCarWebService.GetAllResponse retVal = ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.GetAllResponse> AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.GetAllAsync(AracKiralama.WebUI.RentedCarWebService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.GetAllResponse> GetAllAsync() {
            AracKiralama.WebUI.RentedCarWebService.GetAllRequest inValue = new AracKiralama.WebUI.RentedCarWebService.GetAllRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.GetAllRequestBody();
            return ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.RentedCarWebService.UpdateResponse AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.Update(AracKiralama.WebUI.RentedCarWebService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            AracKiralama.WebUI.RentedCarWebService.UpdateRequest inValue = new AracKiralama.WebUI.RentedCarWebService.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.UpdateRequestBody();
            inValue.Body.car = car;
            AracKiralama.WebUI.RentedCarWebService.UpdateResponse retVal = ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.UpdateResponse> AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.UpdateAsync(AracKiralama.WebUI.RentedCarWebService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.UpdateResponse> UpdateAsync(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            AracKiralama.WebUI.RentedCarWebService.UpdateRequest inValue = new AracKiralama.WebUI.RentedCarWebService.UpdateRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.UpdateRequestBody();
            inValue.Body.car = car;
            return ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AracKiralama.WebUI.RentedCarWebService.InsertResponse AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.Insert(AracKiralama.WebUI.RentedCarWebService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public bool Insert(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            AracKiralama.WebUI.RentedCarWebService.InsertRequest inValue = new AracKiralama.WebUI.RentedCarWebService.InsertRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.InsertRequestBody();
            inValue.Body.car = car;
            AracKiralama.WebUI.RentedCarWebService.InsertResponse retVal = ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.InsertResponse> AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap.InsertAsync(AracKiralama.WebUI.RentedCarWebService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<AracKiralama.WebUI.RentedCarWebService.InsertResponse> InsertAsync(AracKiralama.WebUI.RentedCarWebService.RentedCar car) {
            AracKiralama.WebUI.RentedCarWebService.InsertRequest inValue = new AracKiralama.WebUI.RentedCarWebService.InsertRequest();
            inValue.Body = new AracKiralama.WebUI.RentedCarWebService.InsertRequestBody();
            inValue.Body.car = car;
            return ((AracKiralama.WebUI.RentedCarWebService.RentedCarWebServiceSoap)(this)).InsertAsync(inValue);
        }
    }
}
